### ISSUE TITLE
detectRetina: true breaks

### ISSUE THREAD

**Issue by bsudekum** [tilemapjp/ZoomTMSLayer#1]
Hi,
This is great little plugin, thanks for making it. I'm wondering if you had any insight as to why the plugin breaks when the parameter 'detectRetina: true' is on (leaflet lib). It works great otherwise but when this is on, the tiles do not show up at past max zoom.

Thanks

**Comment by kochizufan** [comment]
Hello, I try to fix this bug in 0.1.1. Please try it.
Thanks for report.

**Comment by bsudekum** [comment]
Awesome, thanks so much! Working great now.
